# Custom Language File for Launcher Customizer

[ejs.app]
title = "한드의 놀이터"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/HanDue-Playground"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/S4QzcJJNzE"
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/HanDue-Playground"
supportLink = "https://github.com/mchlauncher/HanDue-Playground/issues"

[ejs.welcome]
welcomeHeader = "한드의 놀이터"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."